baseURL = "https://wakeupdevs.org/"
# include content marked as draft
buildDrafts = false
# include content with publishdate in the future
buildFuture = false
# include content already expired
buildExpired = false
# enable this to make all relative URLs relative to content root. Note that this does not affect absolute URLs.
relativeURLs = true
disableRSS = true
enableRobotsTXT = true
editor = "nano"
languageCode = "en"
language = "en"
theme = "vncnt-hugo"
title = "Wake Up Devs"

_merge = "none"

[permalinks]
  fixed = ":title/"
  posts = "posts/:slug/"

[params]
  author = "Wake Up Devs"
  # email does still work but is deprecated.
  # use [params.contact.email] instead.
  #email = "john.doe@example.com"
  description = ""
  bio = "Before doing anything you must be awake"
  avatar = "img/logo.png"
  favicon = "img/favicon.ico"
  error404 = "There is no such page."

  [params.contact]
    
    # You may use (inline) tables for more versatility
    # This allows sorting and even more icons.
    # Just make sure not to mix key-value pairs, inline tables and tables,
    # although keeping keeping this order is ok.
    # See https://toml.io/en/v1.0.0 for details
    [params.contact.email] # key names are sorted lexicographically
      icon = "envelope" # may be omitted. defaults to key name
      style = "fas" # may be omitted. default = "fas"
      link = "mailto:info@wakeupdevs.org"
    [params.contact.linkedin]
      style = "fab" # may be omitted. default = "fas"
      link = "https://www.linkedin.com/company/wake-up-devs/"
      # By default rel="me" is not set
      # For some services, it makes sense to set it though.
      # This is the case for Mastodon (and Github) if you link back from these services.
      # See
      # https://microformats.org/wiki/rel-me and
      # https://docs.joinmastodon.org/user/profile/#verification
      # for more information.
      # This defaults to false to cover the case of not having control over the linked site.
      rel-me = true
      
